version: '3'
services:
  ubuntu_nginx:
    build: ../04/.
    container_name: ubuntu_nginx
    restart: always
    volumes:
       - ../01/nginx.conf:/etc/nginx/nginx.conf
  nginx:
     image: nginx:1.17.2-alpine
     container_name: nginx
     restart: always
     ports:
       - 80:8080
     links:
       - ubuntu_nginx
     volumes:
       - ./default.conf:/etc/nginx/conf.d/default.conf
